# Generated by Django 5.1 on 2024-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_document_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('cert_number', models.CharField(max_length=50)),
                ('date_of_completion', models.DateField()),
            ],
        ),
    ]
